title: Consdata - blog techniczny
# the subpath of your site, e.g. /blog
baseurl: "/pl/blog-consdata-tech"
url: "https://www.consdata.com/pl/blog-consdata-tech"

google_analytics: UA-28387432-1

paginate: 5
paginate_path: "/blog/page:num/"

sass:
  sass_dir: _sass
  style: compressed

disqus:
  shortname: consdata-tech

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

  # Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-paginate
